### PR TITLE
Fixes reloading of relationship after params have changed

### LINKED ISSUE #25: Data is not reloaded if initial request returns no results
If the first query for a model returns an empty set then one of the query params is changed the resource will not be reloaded and will continue to return an empty set.

### PR DESCRIPTION
**Pull request by arschmitz**
Save the previous set of query params and if its not the same reload the resource

Fixes #25

### CODE REVIEW

File: addon/mixins/model.js [hunk 1]
```diff
@@ -55,13 +55,16 @@ export default Ember.Mixin.create({
...
     var currentQueryId = queryId++;
+
+    const oldParams = this.get(_queryParamPropertyName, params)
+
     this.set(_queryParamPropertyName, params);
     this.set(_queryIdPropertyName, currentQueryId);
 
     //get the relationship value, reloading if necessary
-    var value = this.reloadRelationship(propertyName);
+    var value = this.reloadRelationship(propertyName, JSON.stringify(params) === JSON.stringify(oldParams));
```
Comment (jboler) [inline addon/mixins/model.js]: Shouldn't this be `JSON.stringify(params) !== JSON.stringify(oldParams)` so that it force reloads the relationship if the params have changed?

Comment (arthur5005) [reply addon/mixins/model.js]: I believe that is correct...
